### ISSUE TITLE
Modules test-data task force master list 

### ISSUE THREAD

**Issue by SPPearce** [nf-core/test-datasets#1243]
Master list for discussions around changes we want/need for the test-data repo, primilarly in the `modules` branch

```[tasklist]
### Tasks
- [ ] Set up a GitHub bot to automatically post links to new PRs into the #request-review or #test-datasets slack channels.
- [ ] Rearrange and rename the `delete_me` folder
- [ ] Determine what we want to do with tools with very specific test data files
- [ ] Organise and document the files that we currently have better, with a better syntax and layout than one massive README with single lines of text.
- [ ] Generate a page on the website to be able to view the current test data
- [ ] Very carefully delete any branches that are unnecessary (especially ones that have already been merged)
- [ ] If we are not allowing links to external git files, then we need to deal with all those files
- [ ] Is there a better way to provide test-data for modules than we currently have, with the two stage process. 
```
